AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cache Buster Microservice
Resources:
  cachePrivateQueueBuilderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cachePrivateQueueBuilder.handler
      Runtime: nodejs12.x
      MemorySize: 128
      CodeUri: src/handlers
      Timeout: 50
      Description: A Lambda function that sends page data to SQS where it will wait to be processed.
      Events:
        CachePages:
          Type: Api
          Properties:
            Path: /cache/pages
            Method: post
        ReloadPages:
          Type: Api
          Properties:
            Path: /reload/pages
            Method: post      
        PurgePages:
          Type: Api
          Properties:
            Path: /purge/pages
            Method: post
        Cachebinaries:
          Type: Api
          Properties:
            Path: /cache/binaries
            Method: post
        ReloadBinaries:
          Type: Api
          Properties:
            Path: /reload/binaries
            Method: post
        PurgeBinaries:
          Type: Api
          Properties:
            Path: /purge/binaries
            Method: post
  cachePrivateQueueProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cachePrivateQueueProcessor.handler
      Runtime: nodejs12.x
      CodeUri: src/handlers
      MemorySize: 128
      Timeout: 50
      Description: A Lambda function that recieves requests from SQS to be processed and sent to Redis and Akamai if the request is valid.
  cachePublicClearPagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cachePublicClearPages.handler
      Runtime: nodejs12.x
      CodeUri: src/handlers
      MemorySize: 128
      Timeout: 50
      Description: A Lambda function that recieves requests from a public endpoint to be processed and sent to Redis and Akamai if the request is valid.
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /pages
            Method: post
  cachePublicClearBinary:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cachePublicClearBinary.handler
      Runtime: nodejs12.x
      CodeUri: src/handlers
      MemorySize: 128
      Timeout: 50
      Description: A Lambda function that recieves requests from a public endpoint to be processed and sent to Redis and Akamai if the request is valid.
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /binary
            Method: post            
  cachePublicClearSingleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cachePublicClearSingle.handler
      Runtime: nodejs12.x
      CodeUri: src/handlers
      MemorySize: 128
      Timeout: 50
      Description: A Lambda function that recieves requests from a public endpoint to be processed and sent to Redis and Akamai if the request is valid.
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /page/{proxy+}
            Method: get
  cachePublicClearSingleBinaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cachePublicClearSingleBinary.handler
      Runtime: nodejs12.x
      CodeUri: src/handlers
      MemorySize: 128
      Timeout: 50
      Description: A Lambda function that recieves requests from a public endpoint to be processed and sent to Redis and Akamai if the request is valid.
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /binary/{proxy+}
            Method: get
Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 50
    Environment:
      Variables:
        STAGE: "uat"
        CACHE_PORT: 6379
        CACHE_URL: "acer-elastic-uat.9gktzd.clustercfg.apne1.cache.amazonaws.com"
        REGION: ap-northeast-1
        SQS_URL: "https://sqs.ap-northeast-1.amazonaws.com/831135969289/ACER-CACHEBUSTER-UAT.fifo"
        AKAMAI_URL: "akab-z6aa4qnbbnadfac6-fguhb6vmst6c4g5n.luna.akamaiapis.net"
        AKAMAI_CLIENT_TOKEN: "akab-xehmvkof6lww5dfr-z7un7asiqk6ghipl"
        AKAMAI_ACCESS_TOKEN: "akab-kepampngeti6srkc-qlzyri4ldcrlbanx"
        AKAMAI_CLIENT_SECRET: "NX9jbAr6iRk3v/59y5IqhDSKNHBRdi036DW5wri5w0I="
    VpcConfig:
        SecurityGroupIds:
          - sg-09270fd5616ed4c67
        SubnetIds:
          - subnet-0f4f973d5d9b82538
          - subnet-05d179bc2415b9c47
  Api:
    EndpointConfiguration: EDGE
    Domain:
      DomainName:  cachebuster-live.agw-uat.acer.com
      CertificateArn: arn:aws:acm:us-east-1:831135969289:certificate/17cc8a97-65b7-4632-b366-0da20d0b0483
      EndpointConfiguration: EDGE
      BasePath:
        - /api